# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: log_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='log_message.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x11log_message.proto\"\\\n\x11\x45valuationMessage\x12\x0c\n\x04loss\x18\x01 \x01(\x02\x12\x0b\n\x03\x61\x63\x63\x18\x02 \x01(\x02\x12\x0c\n\x04\x61\x63\x63\x35\x18\x03 \x01(\x02\x12\x0c\n\x04time\x18\x04 \x01(\x02\x12\x10\n\x08\x65val_num\x18\x05 \x01(\x05\"\xb1\x01\n\x08TrainLog\x12\r\n\x05\x65poch\x18\x01 \x01(\x05\x12\r\n\x05\x62\x61tch\x18\x02 \x01(\x05\x12\x11\n\tbatch_num\x18\x03 \x01(\x05\x12\x12\n\nbatch_loss\x18\x04 \x01(\x02\x12\x11\n\tbatch_acc\x18\x05 \x01(\x02\x12\x15\n\rlearning_rate\x18\x06 \x01(\x02\x12\x0c\n\x04time\x18\x07 \x01(\x02\x12(\n\x0c\x65val_message\x18\x08 \x01(\x0b\x32\x12.EvaluationMessageb\x06proto3')
)




_EVALUATIONMESSAGE = _descriptor.Descriptor(
  name='EvaluationMessage',
  full_name='EvaluationMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='loss', full_name='EvaluationMessage.loss', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='acc', full_name='EvaluationMessage.acc', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='acc5', full_name='EvaluationMessage.acc5', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='EvaluationMessage.time', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='eval_num', full_name='EvaluationMessage.eval_num', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=113,
)


_TRAINLOG = _descriptor.Descriptor(
  name='TrainLog',
  full_name='TrainLog',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='epoch', full_name='TrainLog.epoch', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='batch', full_name='TrainLog.batch', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='batch_num', full_name='TrainLog.batch_num', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='batch_loss', full_name='TrainLog.batch_loss', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='batch_acc', full_name='TrainLog.batch_acc', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='learning_rate', full_name='TrainLog.learning_rate', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='TrainLog.time', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='eval_message', full_name='TrainLog.eval_message', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=293,
)

_TRAINLOG.fields_by_name['eval_message'].message_type = _EVALUATIONMESSAGE
DESCRIPTOR.message_types_by_name['EvaluationMessage'] = _EVALUATIONMESSAGE
DESCRIPTOR.message_types_by_name['TrainLog'] = _TRAINLOG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EvaluationMessage = _reflection.GeneratedProtocolMessageType('EvaluationMessage', (_message.Message,), dict(
  DESCRIPTOR = _EVALUATIONMESSAGE,
  __module__ = 'log_message_pb2'
  # @@protoc_insertion_point(class_scope:EvaluationMessage)
  ))
_sym_db.RegisterMessage(EvaluationMessage)

TrainLog = _reflection.GeneratedProtocolMessageType('TrainLog', (_message.Message,), dict(
  DESCRIPTOR = _TRAINLOG,
  __module__ = 'log_message_pb2'
  # @@protoc_insertion_point(class_scope:TrainLog)
  ))
_sym_db.RegisterMessage(TrainLog)


# @@protoc_insertion_point(module_scope)
